app_composition:
    resource: "@AppBundle/Resources/config/routing/composition.yml"
    prefix:   /composition

app_network:
    resource: "@AppBundle/Resources/config/routing/network.yml"
    prefix:   /network

app_scanhistory:
    resource: "@AppBundle/Resources/config/routing/scanhistory.yml"
    prefix:   /scanhistory

app_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_scan:
    resource: "@AppBundle/Resources/config/routing/scan.yml"
    prefix:   /scan

app_import:
    resource: "@AppBundle/Resources/config/routing/import.yml"
    prefix:   /import
